import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { checkuser, createUser, signOut } from './authAPI';
// import { updateUser } from '../user/userAPI';


const initialState = {
  loggedInUser: null,  // used only for id and role
  status: 'idle',
  // error: null,
  error: {
    login: false,
    signup: false,
    message: "default error"
  }
};


export const createUserAsync = createAsyncThunk(
  'user/createUser',
  async (userdata) => {
    try {
      const response = await createUser(userdata);
      // console.log(response);
      return response.data;
    } catch (error) {
      // console.log(error);
      return error.data
    }
  }
);
// already present in userslice

// export const updateUserAsync = createAsyncThunk(
//   'user/updateUser',
//   async (update) => {
//     const response = await updateUser(update);
//     return response.data;
//   }
// );

export const checkUserAsync = createAsyncThunk(
  'user/checkUser',
  async (loginInfo) => {
    try {
      const response = await checkuser(loginInfo);
      return response.data;
    } catch (error) {
      return error.data
    }
  }
);

export const signOutAsync = createAsyncThunk(
  'user/signout',
  async (userId) => {
    const response = await signOut(userId);
    return response.data;
  }
);


export const authSlice = createSlice({
  name: 'user',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    increment: (state) => {

      state.value += 1;
    },

  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(createUserAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(createUserAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        if (action.payload.message) {
          state.error = {
            login: false,
            signup: true,
            message: action.payload.message
          }
        }
        else
          state.loggedInUser = action.payload;
      })
      // .addCase(createUserAsync.rejected, (state, action) => {
      //   state.status = 'idle';
      //   console.log(action.payload);
      //   state.error = {
      //     signup: true,
      //     message: action.payload
      //   }
      // })
      .addCase(checkUserAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(checkUserAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        if (action.payload.message) {
          state.error = {
            login: true,
            signup: false,
            message: action.payload.message
          }
        }
        else
          state.loggedInUser = action.payload;
      })
      .addCase(checkUserAsync.rejected, (state, action) => {
        state.status = 'idle';
        state.error = action.error;
      })
      // .addCase(updateUserAsync.pending, (state) => {
      //   state.status = 'loading';
      // })
      // .addCase(updateUserAsync.fulfilled, (state, action) => {
      //   state.status = 'idle';
      //   state.loggedInUser = action.payload;
      // })
      .addCase(signOutAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(signOutAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.loggedInUser = null;
      })
  },
});

export const { increment } = authSlice.actions;

export const selectLoggedInUser = (state) => state.user.loggedInUser
export const selectError = (state) => state.user.error

export default authSlice.reducer;
